---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: presage-manager
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - agones.dev
  resources:
  - fleets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/scale
  - replicasets/scale
  - statefulsets/scale
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - scaling.presage.sh
  resources:
  - forecastbackends
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - scaling.presage.sh
  resources:
  - forecastbackends/status
  - predictivescalers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - scaling.presage.sh
  resources:
  - predictivescalers
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scaling.presage.sh
  resources:
  - predictivescalers/finalizers
  verbs:
  - update
