#!/usr/bin/env python3
"""Generate docs/api-reference.md from the CRD schemas.

Hand-written API docs drift the moment someone adds a field, and a reference
that lies is worse than no reference. This reads the generated CRDs, so it can
only be wrong if the CRDs are.
"""

from __future__ import annotations

import pathlib
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "api-reference.md"


def fmt_type(schema: dict) -> str:
    t = schema.get("type", "object")
    if t == "array":
        return f"[]{fmt_type(schema.get('items', {}))}"
    if enum := schema.get("enum"):
        return " \\| ".join(f"`{e}`" for e in enum)
    if schema.get("x-kubernetes-int-or-string"):
        return "int-or-string"
    return f"`{t}`"


def describe(schema: dict) -> str:
    d = (schema.get("description") or "").strip()
    d = " ".join(d.split())
    if default := schema.get("default"):
        d += f" Default: `{default}`."
    return d


def walk(name: str, schema: dict, required: set[str], lines: list[str], depth: int = 0) -> None:
    props = schema.get("properties") or {}
    if not props:
        return
    lines.append(f"\n### {name}\n")
    if desc := describe(schema):
        lines.append(f"{desc}\n")
    lines.append("| Field | Type | Required | Description |")
    lines.append("| --- | --- | --- | --- |")
    nested: list[tuple[str, dict]] = []
    for key, prop in sorted(props.items()):
        req = "yes" if key in required else ""
        lines.append(f"| `{key}` | {fmt_type(prop)} | {req} | {describe(prop)} |")
        target = prop.get("items", prop) if prop.get("type") == "array" else prop
        if target.get("properties"):
            nested.append((f"{name}.{key}", target))
    for child_name, child in nested:
        walk(child_name, child, set(child.get("required") or []), lines, depth + 1)


def main() -> int:
    lines = [
        "# API reference",
        "",
        "<!-- Generated by hack/gen_api_docs.py. Do not edit by hand;",
        "     run `make api-docs` instead. -->",
        "",
        "API group: `scaling.presage.sh`, version `v1alpha1`.",
    ]

    for path in sorted((ROOT / "config" / "crd").glob("*.yaml")):
        crd = yaml.safe_load(path.read_text())
        kind = crd["spec"]["names"]["kind"]
        scope = crd["spec"]["scope"]
        for version in crd["spec"]["versions"]:
            schema = version["schema"]["openAPIV3Schema"]
            lines.append(f"\n## {kind}\n")
            lines.append(f"Scope: {scope}. Version: `{version['name']}`.\n")
            if desc := describe(schema):
                lines.append(f"{desc}\n")
            for section in ("spec", "status"):
                sub = (schema.get("properties") or {}).get(section)
                if sub and sub.get("properties"):
                    walk(f"{kind}.{section}", sub, set(sub.get("required") or []), lines)

    OUT.write_text("\n".join(lines).rstrip() + "\n")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(lines)} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
