//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/intstr"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgonesFleetTarget) DeepCopyInto(out *AgonesFleetTarget) {
	*out = *in
	if in.MaxRecommendationAge != nil {
		in, out := &in.MaxRecommendationAge, &out.MaxRecommendationAge
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgonesFleetTarget.
func (in *AgonesFleetTarget) DeepCopy() *AgonesFleetTarget {
	if in == nil {
		return nil
	}
	out := new(AgonesFleetTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacitySpec) DeepCopyInto(out *CapacitySpec) {
	*out = *in
	if in.PerReplica != nil {
		in, out := &in.PerReplica, &out.PerReplica
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Query != nil {
		in, out := &in.Query, &out.Query
		*out = new(PrometheusSignal)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacitySpec.
func (in *CapacitySpec) DeepCopy() *CapacitySpec {
	if in == nil {
		return nil
	}
	out := new(CapacitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ForecastBackend) DeepCopyInto(out *ForecastBackend) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ForecastBackend.
func (in *ForecastBackend) DeepCopy() *ForecastBackend {
	if in == nil {
		return nil
	}
	out := new(ForecastBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ForecastBackend) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ForecastBackendList) DeepCopyInto(out *ForecastBackendList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ForecastBackend, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ForecastBackendList.
func (in *ForecastBackendList) DeepCopy() *ForecastBackendList {
	if in == nil {
		return nil
	}
	out := new(ForecastBackendList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ForecastBackendList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ForecastBackendSpec) DeepCopyInto(out *ForecastBackendSpec) {
	*out = *in
	if in.TimesFM != nil {
		in, out := &in.TimesFM, &out.TimesFM
		*out = new(TimesFMBackend)
		(*in).DeepCopyInto(*out)
	}
	if in.SeasonalNaive != nil {
		in, out := &in.SeasonalNaive, &out.SeasonalNaive
		*out = new(SeasonalNaiveBackend)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ForecastBackendSpec.
func (in *ForecastBackendSpec) DeepCopy() *ForecastBackendSpec {
	if in == nil {
		return nil
	}
	out := new(ForecastBackendSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ForecastBackendStatus) DeepCopyInto(out *ForecastBackendStatus) {
	*out = *in
	if in.LastProbeTime != nil {
		in, out := &in.LastProbeTime, &out.LastProbeTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ForecastBackendStatus.
func (in *ForecastBackendStatus) DeepCopy() *ForecastBackendStatus {
	if in == nil {
		return nil
	}
	out := new(ForecastBackendStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ForecastSample) DeepCopyInto(out *ForecastSample) {
	*out = *in
	in.GeneratedAt.DeepCopyInto(&out.GeneratedAt)
	if in.Quantiles != nil {
		in, out := &in.Quantiles, &out.Quantiles
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ForecastSample.
func (in *ForecastSample) DeepCopy() *ForecastSample {
	if in == nil {
		return nil
	}
	out := new(ForecastSample)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ForecastSpec) DeepCopyInto(out *ForecastSpec) {
	*out = *in
	if in.BackendRef != nil {
		in, out := &in.BackendRef, &out.BackendRef
		*out = new(string)
		**out = **in
	}
	if in.Horizon != nil {
		in, out := &in.Horizon, &out.Horizon
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ForecastSpec.
func (in *ForecastSpec) DeepCopy() *ForecastSpec {
	if in == nil {
		return nil
	}
	out := new(ForecastSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LeadTimeSpec) DeepCopyInto(out *LeadTimeSpec) {
	*out = *in
	if in.Static != nil {
		in, out := &in.Static, &out.Static
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Observed != nil {
		in, out := &in.Observed, &out.Observed
		*out = new(PrometheusSignal)
		(*in).DeepCopyInto(*out)
	}
	if in.Min != nil {
		in, out := &in.Min, &out.Min
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Max != nil {
		in, out := &in.Max, &out.Max
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LeadTimeSpec.
func (in *LeadTimeSpec) DeepCopy() *LeadTimeSpec {
	if in == nil {
		return nil
	}
	out := new(LeadTimeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicySpec) DeepCopyInto(out *PolicySpec) {
	*out = *in
	if in.ScaleDownUncertaintyGuard != nil {
		in, out := &in.ScaleDownUncertaintyGuard, &out.ScaleDownUncertaintyGuard
		*out = new(UncertaintyGuardSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Headroom != nil {
		in, out := &in.Headroom, &out.Headroom
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.ReactiveFloor != nil {
		in, out := &in.ReactiveFloor, &out.ReactiveFloor
		*out = new(ReactiveFloorSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Stabilization != nil {
		in, out := &in.Stabilization, &out.Stabilization
		*out = new(StabilizationSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicySpec.
func (in *PolicySpec) DeepCopy() *PolicySpec {
	if in == nil {
		return nil
	}
	out := new(PolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredictiveScaler) DeepCopyInto(out *PredictiveScaler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredictiveScaler.
func (in *PredictiveScaler) DeepCopy() *PredictiveScaler {
	if in == nil {
		return nil
	}
	out := new(PredictiveScaler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PredictiveScaler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredictiveScalerList) DeepCopyInto(out *PredictiveScalerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PredictiveScaler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredictiveScalerList.
func (in *PredictiveScalerList) DeepCopy() *PredictiveScalerList {
	if in == nil {
		return nil
	}
	out := new(PredictiveScalerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PredictiveScalerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredictiveScalerSpec) DeepCopyInto(out *PredictiveScalerSpec) {
	*out = *in
	in.ScaleTargetRef.DeepCopyInto(&out.ScaleTargetRef)
	in.Signal.DeepCopyInto(&out.Signal)
	in.Policy.DeepCopyInto(&out.Policy)
	if in.LeadTime != nil {
		in, out := &in.LeadTime, &out.LeadTime
		*out = new(LeadTimeSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Capacity != nil {
		in, out := &in.Capacity, &out.Capacity
		*out = new(CapacitySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Forecast != nil {
		in, out := &in.Forecast, &out.Forecast
		*out = new(ForecastSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredictiveScalerSpec.
func (in *PredictiveScalerSpec) DeepCopy() *PredictiveScalerSpec {
	if in == nil {
		return nil
	}
	out := new(PredictiveScalerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredictiveScalerStatus) DeepCopyInto(out *PredictiveScalerStatus) {
	*out = *in
	if in.Breakdown != nil {
		in, out := &in.Breakdown, &out.Breakdown
		*out = new(RecommendationBreakdown)
		(*in).DeepCopyInto(*out)
	}
	if in.LastForecast != nil {
		in, out := &in.LastForecast, &out.LastForecast
		*out = new(ForecastSample)
		(*in).DeepCopyInto(*out)
	}
	if in.LastScaleTime != nil {
		in, out := &in.LastScaleTime, &out.LastScaleTime
		*out = (*in).DeepCopy()
	}
	if in.ScaleDownCandidateSince != nil {
		in, out := &in.ScaleDownCandidateSince, &out.ScaleDownCandidateSince
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredictiveScalerStatus.
func (in *PredictiveScalerStatus) DeepCopy() *PredictiveScalerStatus {
	if in == nil {
		return nil
	}
	out := new(PredictiveScalerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusSignal) DeepCopyInto(out *PrometheusSignal) {
	*out = *in
	if in.BearerTokenSecretRef != nil {
		in, out := &in.BearerTokenSecretRef, &out.BearerTokenSecretRef
		*out = new(SecretKeySelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusSignal.
func (in *PrometheusSignal) DeepCopy() *PrometheusSignal {
	if in == nil {
		return nil
	}
	out := new(PrometheusSignal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReactiveFloorSpec) DeepCopyInto(out *ReactiveFloorSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.BufferSize != nil {
		in, out := &in.BufferSize, &out.BufferSize
		*out = new(intstr.IntOrString)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReactiveFloorSpec.
func (in *ReactiveFloorSpec) DeepCopy() *ReactiveFloorSpec {
	if in == nil {
		return nil
	}
	out := new(ReactiveFloorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecommendationBreakdown) DeepCopyInto(out *RecommendationBreakdown) {
	*out = *in
	if in.Reactive != nil {
		in, out := &in.Reactive, &out.Reactive
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecommendationBreakdown.
func (in *RecommendationBreakdown) DeepCopy() *RecommendationBreakdown {
	if in == nil {
		return nil
	}
	out := new(RecommendationBreakdown)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaleTargetRef) DeepCopyInto(out *ScaleTargetRef) {
	*out = *in
	if in.Agones != nil {
		in, out := &in.Agones, &out.Agones
		*out = new(AgonesFleetTarget)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaleTargetRef.
func (in *ScaleTargetRef) DeepCopy() *ScaleTargetRef {
	if in == nil {
		return nil
	}
	out := new(ScaleTargetRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeasonalNaiveBackend) DeepCopyInto(out *SeasonalNaiveBackend) {
	*out = *in
	if in.Season != nil {
		in, out := &in.Season, &out.Season
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeasonalNaiveBackend.
func (in *SeasonalNaiveBackend) DeepCopy() *SeasonalNaiveBackend {
	if in == nil {
		return nil
	}
	out := new(SeasonalNaiveBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeySelector) DeepCopyInto(out *SecretKeySelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeySelector.
func (in *SecretKeySelector) DeepCopy() *SecretKeySelector {
	if in == nil {
		return nil
	}
	out := new(SecretKeySelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SignalSpec) DeepCopyInto(out *SignalSpec) {
	*out = *in
	if in.Prometheus != nil {
		in, out := &in.Prometheus, &out.Prometheus
		*out = new(PrometheusSignal)
		(*in).DeepCopyInto(*out)
	}
	if in.Resolution != nil {
		in, out := &in.Resolution, &out.Resolution
		*out = new(v1.Duration)
		**out = **in
	}
	if in.History != nil {
		in, out := &in.History, &out.History
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SignalSpec.
func (in *SignalSpec) DeepCopy() *SignalSpec {
	if in == nil {
		return nil
	}
	out := new(SignalSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StabilizationSpec) DeepCopyInto(out *StabilizationSpec) {
	*out = *in
	if in.ScaleDownWindow != nil {
		in, out := &in.ScaleDownWindow, &out.ScaleDownWindow
		*out = new(v1.Duration)
		**out = **in
	}
	if in.MaxScaleUpRate != nil {
		in, out := &in.MaxScaleUpRate, &out.MaxScaleUpRate
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.MaxScaleDownRate != nil {
		in, out := &in.MaxScaleDownRate, &out.MaxScaleDownRate
		*out = new(intstr.IntOrString)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StabilizationSpec.
func (in *StabilizationSpec) DeepCopy() *StabilizationSpec {
	if in == nil {
		return nil
	}
	out := new(StabilizationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimesFMBackend) DeepCopyInto(out *TimesFMBackend) {
	*out = *in
	if in.UseQuantileHead != nil {
		in, out := &in.UseQuantileHead, &out.UseQuantileHead
		*out = new(bool)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimesFMBackend.
func (in *TimesFMBackend) DeepCopy() *TimesFMBackend {
	if in == nil {
		return nil
	}
	out := new(TimesFMBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UncertaintyGuardSpec) DeepCopyInto(out *UncertaintyGuardSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UncertaintyGuardSpec.
func (in *UncertaintyGuardSpec) DeepCopy() *UncertaintyGuardSpec {
	if in == nil {
		return nil
	}
	out := new(UncertaintyGuardSpec)
	in.DeepCopyInto(out)
	return out
}
