apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manager/namespace.yaml
  - crd/scaling.presage.sh_predictivescalers.yaml
  - crd/scaling.presage.sh_forecastbackends.yaml
  - rbac/service_account.yaml
  - rbac/role.yaml
  - rbac/role_binding.yaml
  - manager/manager.yaml
  - manager/forecaster.yaml
