{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "presage.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "presage.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}{{- toYaml . | nindent 4 }}{{- end }}
spec:
  selector:
    matchLabels:
      {{- include "presage.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames: [{{ .Release.Namespace }}]
  endpoints:
    - port: metrics
      interval: {{ .Values.metrics.serviceMonitor.interval }}
{{- end }}
{{- if and .Values.metrics.enabled .Values.metrics.vmServiceScrape.enabled }}
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: {{ include "presage.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "presage.labels" . | nindent 4 }}
    {{- with .Values.metrics.vmServiceScrape.labels }}{{- toYaml . | nindent 4 }}{{- end }}
spec:
  selector:
    matchLabels:
      {{- include "presage.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames: [{{ .Release.Namespace }}]
  endpoints:
    - port: metrics
      interval: {{ .Values.metrics.vmServiceScrape.interval }}
{{- end }}
